-- Part 4/9 — Models (Tesla … Bentley, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('Tesla', 'Model S', 'sedan'),
  ('Tesla', 'Model X', 'suv'),
  ('Tesla', 'Cybertruck', 'pickup'),
  ('Tesla', 'Roadster', 'convertible'),
  ('Tesla', 'Semi', 'other'),
  ('Tesla', 'Model 3 Highland', 'sedan'),
  ('Tesla', 'Model Y Juniper', 'suv'),
  ('Tesla', 'Model 3 Hybrid', 'sedan'),
  ('Tesla', 'Model 3 Electric', 'sedan'),
  ('Tesla', 'Model 3 Plug-in Hybrid', 'sedan'),
  ('Tesla', 'Model 3 Touring', 'wagon'),
  ('Tesla', 'Model 3 Sport', 'suv'),
  ('Tesla', 'Model 3 Limited', 'sedan'),
  ('Rivian', 'R1T', 'pickup'),
  ('Rivian', 'R1S', 'other'),
  ('Rivian', 'R2', 'other'),
  ('Rivian', 'R3', 'other'),
  ('Rivian', 'R3X', 'other'),
  ('Rivian', 'EDV 700', 'other'),
  ('Rivian', 'EDV 500', 'other'),
  ('Rivian', 'Amazon Delivery Van', 'other'),
  ('Rivian', 'R1T Hybrid', 'pickup'),
  ('Rivian', 'R1T Electric', 'pickup'),
  ('Rivian', 'R1T Plug-in Hybrid', 'pickup'),
  ('Rivian', 'R1T Touring', 'pickup'),
  ('Rivian', 'R1T Sport', 'pickup'),
  ('Rivian', 'R1T Limited', 'pickup'),
  ('Rivian', 'R1T Premium', 'pickup'),
  ('Lucid', 'Air Pure', 'sedan'),
  ('Lucid', 'Air Touring', 'wagon'),
  ('Lucid', 'Air Grand Touring', 'wagon'),
  ('Lucid', 'Air Sapphire', 'sedan'),
  ('Lucid', 'Air Dream Edition', 'sedan'),
  ('Lucid', 'Gravity', 'other'),
  ('Lucid', 'Air Midnight Dream', 'sedan'),
  ('Lucid', 'Air Stealth', 'sedan'),
  ('Lucid', 'Air GT', 'coupe'),
  ('Lucid', 'Air Pure Hybrid', 'sedan'),
  ('Lucid', 'Air Pure Electric', 'sedan'),
  ('Lucid', 'Air Pure Plug-in Hybrid', 'sedan'),
  ('Lucid', 'Air Pure Touring', 'wagon'),
  ('Lucid', 'Air Pure Sport', 'suv'),
  ('Lucid', 'Air Pure Limited', 'sedan'),
  ('Volvo', 'S60', 'other'),
  ('Volvo', 'S90', 'other'),
  ('Volvo', 'V60', 'wagon'),
  ('Volvo', 'V90', 'wagon'),
  ('Volvo', 'XC40', 'other'),
  ('Volvo', 'XC60', 'other'),
  ('Volvo', 'XC90', 'other'),
  ('Volvo', 'C40', 'other'),
  ('Volvo', 'EX30', 'suv'),
  ('Volvo', 'EX90', 'suv'),
  ('Volvo', '850', 'other'),
  ('Volvo', '240', 'other'),
  ('Volvo', '740', 'other'),
  ('Volvo', '940', 'other'),
  ('Volvo', 'S40', 'other'),
  ('Volvo', 'V40', 'other'),
  ('Volvo', 'C30', 'other'),
  ('Volvo', 'XC70', 'other'),
  ('Volvo', 'S80', 'other'),
  ('Polestar', 'Polestar 1', 'other'),
  ('Polestar', 'Polestar 2', 'other'),
  ('Polestar', 'Polestar 3', 'other'),
  ('Polestar', 'Polestar 4', 'other'),
  ('Polestar', 'Polestar 5', 'other'),
  ('Polestar', 'Polestar 6', 'other'),
  ('Polestar', 'Polestar BST', 'other'),
  ('Polestar', 'Polestar 2 Long Range', 'other'),
  ('Polestar', 'Polestar 3 Performance', 'other'),
  ('Polestar', 'Polestar 1 Hybrid', 'other'),
  ('Polestar', 'Polestar 1 Electric', 'other'),
  ('Polestar', 'Polestar 1 Plug-in Hybrid', 'other'),
  ('Polestar', 'Polestar 1 Touring', 'wagon'),
  ('Polestar', 'Polestar 1 Sport', 'suv'),
  ('Polestar', 'Polestar 1 Limited', 'other'),
  ('Peugeot', '208', 'other'),
  ('Peugeot', '308', 'other'),
  ('Peugeot', '408', 'other'),
  ('Peugeot', '508', 'other'),
  ('Peugeot', '2008', 'other'),
  ('Peugeot', '3008', 'other'),
  ('Peugeot', '5008', 'other'),
  ('Peugeot', 'Rifter', 'other'),
  ('Peugeot', 'Traveller', 'other'),
  ('Peugeot', 'Partner', 'other'),
  ('Peugeot', 'e-208', 'other'),
  ('Peugeot', 'e-2008', 'other'),
  ('Peugeot', 'e-308', 'other'),
  ('Peugeot', 'RCZ', 'other'),
  ('Peugeot', '206', 'other'),
  ('Peugeot', '207', 'other'),
  ('Peugeot', '307', 'other'),
  ('Peugeot', '407', 'other'),
  ('Peugeot', '607', 'other'),
  ('Peugeot', '106', 'other'),
  ('Citroen', 'C3', 'other'),
  ('Citroen', 'C4', 'other'),
  ('Citroen', 'C5 Aircross', 'other'),
  ('Citroen', 'C5 X', 'other'),
  ('Citroen', 'Berlingo', 'other'),
  ('Citroen', 'SpaceTourer', 'other'),
  ('Citroen', 'Ami', 'other'),
  ('Citroen', 'e-C4', 'other'),
  ('Citroen', 'DS3', 'other'),
  ('Citroen', 'C1', 'other'),
  ('Citroen', 'C2', 'other'),
  ('Citroen', 'C-Elysee', 'other'),
  ('Citroen', 'Xsara', 'other'),
  ('Citroen', 'Xantia', 'other'),
  ('Citroen', 'C6', 'other'),
  ('Citroen', 'C8', 'other'),
  ('Citroen', 'Saxo', 'other'),
  ('Citroen', 'Nemo', 'other'),
  ('Renault', 'Clio', 'other'),
  ('Renault', 'Megane', 'other'),
  ('Renault', 'Captur', 'other'),
  ('Renault', 'Arkana', 'other'),
  ('Renault', 'Kadjar', 'other'),
  ('Renault', 'Koleos', 'other'),
  ('Renault', 'Scenic', 'other'),
  ('Renault', 'Espace', 'van'),
  ('Renault', 'Talisman', 'other'),
  ('Renault', 'Zoe', 'other'),
  ('Renault', 'Twingo', 'other'),
  ('Renault', 'Fluence', 'other'),
  ('Renault', 'Laguna', 'other'),
  ('Renault', 'Symbol', 'other'),
  ('Renault', 'Duster', 'other'),
  ('Renault', 'Sandero', 'other'),
  ('Renault', 'Logan', 'other'),
  ('Renault', 'Kangoo', 'other'),
  ('Renault', 'Austral', 'other'),
  ('Dacia', 'Sandero', 'other'),
  ('Dacia', 'Logan', 'other'),
  ('Dacia', 'Duster', 'other'),
  ('Dacia', 'Jogger', 'other'),
  ('Dacia', 'Spring', 'other'),
  ('Dacia', 'Lodgy', 'other'),
  ('Dacia', 'Dokker', 'other'),
  ('Dacia', '1300', 'other'),
  ('Dacia', '1310', 'other'),
  ('Dacia', 'Pick-Up', 'other'),
  ('Dacia', 'Bigster', 'other'),
  ('Dacia', 'Manifesto', 'other'),
  ('Dacia', 'Solenza', 'other'),
  ('Dacia', 'Nova', 'other'),
  ('Dacia', 'Sandero Hybrid', 'other'),
  ('Dacia', 'Sandero Electric', 'other'),
  ('Dacia', 'Sandero Plug-in Hybrid', 'other'),
  ('Dacia', 'Sandero Touring', 'wagon'),
  ('Fiat', '500', 'other'),
  ('Fiat', '500X', 'other'),
  ('Fiat', '500L', 'other'),
  ('Fiat', 'Panda', 'other'),
  ('Fiat', 'Tipo', 'other'),
  ('Fiat', 'Punto', 'other'),
  ('Fiat', 'Bravo', 'other'),
  ('Fiat', 'Linea', 'other'),
  ('Fiat', 'Uno', 'other'),
  ('Fiat', 'Palio', 'other'),
  ('Fiat', 'Siena', 'other'),
  ('Fiat', 'Mobi', 'other'),
  ('Fiat', 'Argo', 'other'),
  ('Fiat', 'Cronos', 'other'),
  ('Fiat', 'Fastback', 'other'),
  ('Fiat', 'Pulse', 'other'),
  ('Fiat', 'Strada', 'other'),
  ('Fiat', 'Doblo', 'other'),
  ('Fiat', 'Freemont', 'other'),
  ('Alfa Romeo', 'Giulia', 'other'),
  ('Alfa Romeo', 'Stelvio', 'other'),
  ('Alfa Romeo', 'Tonale', 'other'),
  ('Alfa Romeo', 'Giulietta', 'other'),
  ('Alfa Romeo', 'MiTo', 'other'),
  ('Alfa Romeo', '4C', 'other'),
  ('Alfa Romeo', 'Spider', 'convertible'),
  ('Alfa Romeo', 'GTV', 'other'),
  ('Alfa Romeo', 'Brera', 'other'),
  ('Alfa Romeo', '159', 'other'),
  ('Alfa Romeo', '156', 'other'),
  ('Alfa Romeo', '147', 'other'),
  ('Alfa Romeo', '166', 'other'),
  ('Alfa Romeo', 'GT', 'coupe'),
  ('Alfa Romeo', '8C Competizione', 'other'),
  ('Alfa Romeo', '33', 'other'),
  ('Alfa Romeo', '75', 'other'),
  ('Alfa Romeo', '90', 'other'),
  ('Maserati', 'Ghibli', 'other'),
  ('Maserati', 'Quattroporte', 'other'),
  ('Maserati', 'Levante', 'other'),
  ('Maserati', 'Grecale', 'other'),
  ('Maserati', 'GranTurismo', 'other'),
  ('Maserati', 'GranCabrio', 'other'),
  ('Maserati', 'MC20', 'coupe'),
  ('Maserati', 'Coupe', 'coupe'),
  ('Maserati', 'Spyder', 'convertible'),
  ('Maserati', '3200 GT', 'coupe'),
  ('Maserati', 'Biturbo', 'other'),
  ('Maserati', 'Shamal', 'other'),
  ('Maserati', 'Karif', 'other'),
  ('Maserati', 'Bora', 'other'),
  ('Maserati', 'Merak', 'other'),
  ('Maserati', 'Ghibli Hybrid', 'other'),
  ('Maserati', 'Ghibli Electric', 'other'),
  ('Maserati', 'Ghibli Plug-in Hybrid', 'other'),
  ('Ferrari', 'Roma', 'coupe'),
  ('Ferrari', 'Portofino', 'coupe'),
  ('Ferrari', '296 GTB', 'coupe'),
  ('Ferrari', '296 GTS', 'coupe'),
  ('Ferrari', 'SF90 Stradale', 'coupe'),
  ('Ferrari', 'SF90 Spider', 'coupe'),
  ('Ferrari', '812 Superfast', 'coupe'),
  ('Ferrari', '812 GTS', 'coupe'),
  ('Ferrari', 'F8 Tributo', 'coupe'),
  ('Ferrari', 'F8 Spider', 'coupe'),
  ('Ferrari', '488 GTB', 'coupe'),
  ('Ferrari', '488 Pista', 'coupe'),
  ('Ferrari', 'LaFerrari', 'other'),
  ('Ferrari', 'California', 'other'),
  ('Ferrari', '458 Italia', 'other'),
  ('Ferrari', 'Enzo', 'other'),
  ('Ferrari', 'F12', 'other'),
  ('Ferrari', 'GTC4Lusso', 'other'),
  ('Lamborghini', 'Urus', 'suv'),
  ('Lamborghini', 'Huracan', 'other'),
  ('Lamborghini', 'Revuelto', 'coupe'),
  ('Lamborghini', 'Aventador', 'other'),
  ('Lamborghini', 'Gallardo', 'other'),
  ('Lamborghini', 'Murcielago', 'other'),
  ('Lamborghini', 'Diablo', 'other'),
  ('Lamborghini', 'Countach', 'other'),
  ('Lamborghini', 'Miura', 'other'),
  ('Lamborghini', 'Espada', 'other'),
  ('Lamborghini', 'Jalpa', 'other'),
  ('Lamborghini', 'Centenario', 'other'),
  ('Lamborghini', 'Sian', 'other'),
  ('Lamborghini', 'Temerario', 'other'),
  ('Lamborghini', 'Sterrato', 'other'),
  ('Lamborghini', 'Huracan STO', 'other'),
  ('Lamborghini', 'Huracan Tecnica', 'other'),
  ('Lamborghini', 'Urus Hybrid', 'suv'),
  ('Bentley', 'Continental GT', 'coupe'),
  ('Bentley', 'Continental GTC', 'other'),
  ('Bentley', 'Flying Spur', 'other'),
  ('Bentley', 'Bentayga', 'suv'),
  ('Bentley', 'Mulsanne', 'other'),
  ('Bentley', 'Azure', 'other'),
  ('Bentley', 'Brooklands', 'other')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
