-- Part 1/9 — vehicle_makes (run FIRST)
BEGIN;

INSERT INTO public.vehicle_makes (name, category)
VALUES
  ('Toyota', 'car'),
  ('Honda', 'car'),
  ('Nissan', 'car'),
  ('Mazda', 'car'),
  ('Subaru', 'car'),
  ('Mitsubishi', 'car'),
  ('Suzuki', 'car'),
  ('Lexus', 'car'),
  ('Infiniti', 'car'),
  ('Acura', 'car'),
  ('BMW', 'car'),
  ('Mercedes-Benz', 'car'),
  ('Audi', 'car'),
  ('Volkswagen', 'car'),
  ('Porsche', 'car'),
  ('Opel', 'car'),
  ('Ford', 'car'),
  ('Chevrolet', 'car'),
  ('GMC', 'car'),
  ('Cadillac', 'car'),
  ('Lincoln', 'car'),
  ('Chrysler', 'car'),
  ('Dodge', 'car'),
  ('Jeep', 'car'),
  ('Ram', 'car'),
  ('Tesla', 'car'),
  ('Rivian', 'car'),
  ('Lucid', 'car'),
  ('Volvo', 'car'),
  ('Polestar', 'car'),
  ('Peugeot', 'car'),
  ('Citroen', 'car'),
  ('Renault', 'car'),
  ('Dacia', 'car'),
  ('Fiat', 'car'),
  ('Alfa Romeo', 'car'),
  ('Maserati', 'car'),
  ('Ferrari', 'car'),
  ('Lamborghini', 'car'),
  ('Bentley', 'car'),
  ('Rolls-Royce', 'car'),
  ('Aston Martin', 'car'),
  ('Jaguar', 'car'),
  ('Land Rover', 'car'),
  ('Mini', 'car'),
  ('Hyundai', 'car'),
  ('Kia', 'car'),
  ('Genesis', 'car'),
  ('SsangYong', 'car'),
  ('Skoda', 'car'),
  ('SEAT', 'car'),
  ('Cupra', 'car'),
  ('BYD', 'car'),
  ('NIO', 'car'),
  ('MG', 'car'),
  ('Geely', 'car'),
  ('Chery', 'car'),
  ('Haval', 'car'),
  ('Tata', 'car'),
  ('Mahindra', 'car'),
  ('Smart', 'car'),
  ('Mercedes-Benz Vans', 'minivan'),
  ('Volkswagen Van', 'minivan'),
  ('Ford Tourneo', 'minivan'),
  ('Renault Passenger', 'minivan'),
  ('Nissan Passenger Van', 'minivan'),
  ('Peugeot Traveller', 'minivan'),
  ('Citroen SpaceTourer', 'minivan'),
  ('Opel Zafira Life', 'minivan'),
  ('Fiat Ulysse', 'minivan'),
  ('Toyota HiAce', 'minivan'),
  ('Mercedes-Benz Sprinter', 'minibus'),
  ('Ford Transit', 'minibus'),
  ('Volkswagen Crafter', 'minibus'),
  ('Iveco Daily', 'minibus'),
  ('Renault Master', 'minibus'),
  ('Peugeot Boxer', 'minibus'),
  ('Fiat Ducato', 'minibus'),
  ('Nissan Interstar', 'minibus'),
  ('Opel Movano', 'minibus'),
  ('MAN TGE', 'minibus'),
  ('Toyota Commuter', 'minibus'),
  ('LDV', 'minibus'),
  ('Mercedes-Benz Coaches', 'bus'),
  ('Volvo Coaches', 'bus'),
  ('Scania', 'bus'),
  ('MAN Coaches', 'bus'),
  ('Setra', 'bus'),
  ('Neoplan', 'bus'),
  ('Van Hool', 'bus'),
  ('Irizar', 'bus'),
  ('Prevost', 'bus'),
  ('MCI', 'bus'),
  ('Yutong', 'bus'),
  ('King Long', 'bus'),
  ('BYD Coaches', 'bus'),
  ('Solaris', 'bus'),
  ('Temsa', 'bus'),
  ('Mercedes-Benz Special', 'special'),
  ('Ford Special', 'special'),
  ('Toyota Special', 'special'),
  ('Rolls-Royce Special', 'special'),
  ('BMW Special', 'special'),
  ('Cadillac Special', 'special'),
  ('Lincoln Special', 'special')
ON CONFLICT (name) DO NOTHING;
