-- Part 3/9 — Models (Audi … Tesla, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('Audi', 'A7', 'other'),
  ('Audi', 'A8', 'sedan'),
  ('Audi', 'Q3', 'suv'),
  ('Audi', 'Q4 e-tron', 'suv'),
  ('Audi', 'Q5', 'suv'),
  ('Audi', 'Q7', 'suv'),
  ('Audi', 'Q8', 'suv'),
  ('Audi', 'e-tron', 'suv'),
  ('Audi', 'e-tron GT', 'suv'),
  ('Audi', 'TT', 'coupe'),
  ('Audi', 'R8', 'other'),
  ('Audi', 'RS3', 'other'),
  ('Audi', 'RS5', 'other'),
  ('Audi', 'RS6', 'other'),
  ('Audi', 'RS7', 'other'),
  ('Audi', 'S3', 'other'),
  ('Audi', 'S4', 'other'),
  ('Audi', 'S5', 'other'),
  ('Audi', 'S6', 'other'),
  ('Audi', 'S8', 'other'),
  ('Audi', 'Q8 e-tron', 'suv'),
  ('Volkswagen', 'Golf', 'hatchback'),
  ('Volkswagen', 'Jetta', 'sedan'),
  ('Volkswagen', 'Passat', 'sedan'),
  ('Volkswagen', 'Arteon', 'other'),
  ('Volkswagen', 'Tiguan', 'suv'),
  ('Volkswagen', 'Atlas', 'suv'),
  ('Volkswagen', 'Taos', 'suv'),
  ('Volkswagen', 'ID.4', 'other'),
  ('Volkswagen', 'ID.7', 'other'),
  ('Volkswagen', 'ID. Buzz', 'other'),
  ('Volkswagen', 'Polo', 'hatchback'),
  ('Volkswagen', 'T-Roc', 'other'),
  ('Volkswagen', 'T-Cross', 'other'),
  ('Volkswagen', 'Touran', 'other'),
  ('Volkswagen', 'Scirocco', 'other'),
  ('Volkswagen', 'Beetle', 'other'),
  ('Volkswagen', 'CC', 'other'),
  ('Volkswagen', 'Phaeton', 'other'),
  ('Volkswagen', 'Amarok', 'pickup'),
  ('Volkswagen', 'Teramont', 'other'),
  ('Porsche', '911', 'coupe'),
  ('Porsche', '718 Boxster', 'coupe'),
  ('Porsche', '718 Cayman', 'coupe'),
  ('Porsche', 'Panamera', 'other'),
  ('Porsche', 'Macan', 'suv'),
  ('Porsche', 'Cayenne', 'suv'),
  ('Porsche', 'Taycan', 'other'),
  ('Porsche', 'Carrera', 'other'),
  ('Porsche', 'Turbo S', 'other'),
  ('Porsche', 'GT3', 'other'),
  ('Porsche', 'GT4', 'other'),
  ('Porsche', 'Cayman', 'other'),
  ('Porsche', 'Boxster', 'other'),
  ('Porsche', 'Macan Electric', 'suv'),
  ('Porsche', 'Cayenne Coupe', 'suv'),
  ('Porsche', 'Panamera Sport Turismo', 'suv'),
  ('Porsche', '911 Hybrid', 'coupe'),
  ('Porsche', '911 Electric', 'coupe'),
  ('Opel', 'Corsa', 'other'),
  ('Opel', 'Astra', 'other'),
  ('Opel', 'Insignia', 'other'),
  ('Opel', 'Mokka', 'other'),
  ('Opel', 'Crossland', 'other'),
  ('Opel', 'Grandland', 'other'),
  ('Opel', 'Combo', 'other'),
  ('Opel', 'Zafira', 'van'),
  ('Opel', 'Adam', 'other'),
  ('Opel', 'Karl', 'other'),
  ('Opel', 'Ampera', 'other'),
  ('Opel', 'Ampera-e', 'other'),
  ('Opel', 'Vectra', 'other'),
  ('Opel', 'Omega', 'other'),
  ('Opel', 'Meriva', 'other'),
  ('Opel', 'Agila', 'other'),
  ('Opel', 'Tigra', 'other'),
  ('Opel', 'Speedster', 'other'),
  ('Ford', 'Mustang', 'coupe'),
  ('Ford', 'Fusion', 'other'),
  ('Ford', 'Focus', 'hatchback'),
  ('Ford', 'Fiesta', 'hatchback'),
  ('Ford', 'Taurus', 'suv'),
  ('Ford', 'Explorer', 'suv'),
  ('Ford', 'Expedition', 'suv'),
  ('Ford', 'Edge', 'suv'),
  ('Ford', 'Escape', 'suv'),
  ('Ford', 'Bronco', 'suv'),
  ('Ford', 'Bronco Sport', 'suv'),
  ('Ford', 'Ranger', 'pickup'),
  ('Ford', 'F-150', 'pickup'),
  ('Ford', 'F-150 Lightning', 'pickup'),
  ('Ford', 'Maverick', 'other'),
  ('Ford', 'EcoSport', 'suv'),
  ('Ford', 'Flex', 'other'),
  ('Ford', 'GT', 'coupe'),
  ('Ford', 'Mach-E', 'other'),
  ('Ford', 'Puma', 'other'),
  ('Ford', 'Kuga', 'other'),
  ('Ford', 'Mondeo', 'other'),
  ('Ford', 'Galaxy', 'van'),
  ('Chevrolet', 'Malibu', 'sedan'),
  ('Chevrolet', 'Impala', 'sedan'),
  ('Chevrolet', 'Camaro', 'coupe'),
  ('Chevrolet', 'Corvette', 'coupe'),
  ('Chevrolet', 'Equinox', 'other'),
  ('Chevrolet', 'Traverse', 'other'),
  ('Chevrolet', 'Tahoe', 'suv'),
  ('Chevrolet', 'Suburban', 'suv'),
  ('Chevrolet', 'Blazer', 'other'),
  ('Chevrolet', 'Trax', 'other'),
  ('Chevrolet', 'Trailblazer', 'other'),
  ('Chevrolet', 'Colorado', 'pickup'),
  ('Chevrolet', 'Silverado', 'pickup'),
  ('Chevrolet', 'Bolt EV', 'other'),
  ('Chevrolet', 'Bolt EUV', 'other'),
  ('Chevrolet', 'Spark', 'other'),
  ('Chevrolet', 'Cruze', 'other'),
  ('Chevrolet', 'Sonic', 'other'),
  ('Chevrolet', 'Volt', 'other'),
  ('Chevrolet', 'Aveo', 'other'),
  ('Chevrolet', 'Captiva', 'other'),
  ('Chevrolet', 'Orlando', 'other'),
  ('GMC', 'Sierra', 'pickup'),
  ('GMC', 'Canyon', 'pickup'),
  ('GMC', 'Yukon', 'suv'),
  ('GMC', 'Yukon XL', 'suv'),
  ('GMC', 'Acadia', 'other'),
  ('GMC', 'Terrain', 'other'),
  ('GMC', 'Envoy', 'other'),
  ('GMC', 'Savana', 'other'),
  ('GMC', 'Hummer EV', 'other'),
  ('GMC', 'Hummer EV SUV', 'suv'),
  ('GMC', 'Typhoon', 'other'),
  ('GMC', 'Jimmy', 'other'),
  ('GMC', 'Sonoma', 'other'),
  ('GMC', 'Safari', 'other'),
  ('GMC', 'Denali', 'other'),
  ('GMC', 'Sierra EV', 'pickup'),
  ('GMC', 'Sierra Hybrid', 'pickup'),
  ('GMC', 'Sierra Electric', 'pickup'),
  ('Cadillac', 'CT4', 'other'),
  ('Cadillac', 'CT5', 'sedan'),
  ('Cadillac', 'CT6', 'other'),
  ('Cadillac', 'XT4', 'suv'),
  ('Cadillac', 'XT5', 'suv'),
  ('Cadillac', 'XT6', 'suv'),
  ('Cadillac', 'Escalade', 'suv'),
  ('Cadillac', 'Lyriq', 'other'),
  ('Cadillac', 'Celestiq', 'other'),
  ('Cadillac', 'ATS', 'other'),
  ('Cadillac', 'CTS', 'sedan'),
  ('Cadillac', 'XTS', 'other'),
  ('Cadillac', 'SRX', 'other'),
  ('Cadillac', 'DTS', 'other'),
  ('Cadillac', 'DeVille', 'other'),
  ('Cadillac', 'Seville', 'other'),
  ('Cadillac', 'Eldorado', 'other'),
  ('Cadillac', 'Fleetwood', 'other'),
  ('Lincoln', 'Navigator', 'suv'),
  ('Lincoln', 'Aviator', 'suv'),
  ('Lincoln', 'Nautilus', 'suv'),
  ('Lincoln', 'Corsair', 'suv'),
  ('Lincoln', 'Continental', 'other'),
  ('Lincoln', 'MKZ', 'other'),
  ('Lincoln', 'MKX', 'other'),
  ('Lincoln', 'MKT', 'other'),
  ('Lincoln', 'Town Car', 'other'),
  ('Lincoln', 'Mark LT', 'other'),
  ('Lincoln', 'LS', 'other'),
  ('Lincoln', 'Zephyr', 'other'),
  ('Lincoln', 'Blackwood', 'other'),
  ('Lincoln', 'Corsair Grand Touring', 'suv'),
  ('Lincoln', 'Navigator Hybrid', 'suv'),
  ('Lincoln', 'Navigator Electric', 'suv'),
  ('Lincoln', 'Navigator Plug-in Hybrid', 'suv'),
  ('Lincoln', 'Navigator Touring', 'suv'),
  ('Chrysler', '300', 'other'),
  ('Chrysler', 'Pacifica', 'van'),
  ('Chrysler', 'Voyager', 'van'),
  ('Chrysler', '200', 'other'),
  ('Chrysler', 'Sebring', 'other'),
  ('Chrysler', 'PT Cruiser', 'other'),
  ('Chrysler', 'Aspen', 'other'),
  ('Chrysler', 'Crossfire', 'other'),
  ('Chrysler', 'Concorde', 'other'),
  ('Chrysler', 'LHS', 'other'),
  ('Chrysler', 'Town and Country', 'other'),
  ('Chrysler', 'Cirrus', 'other'),
  ('Chrysler', 'Neon', 'other'),
  ('Chrysler', 'LeBaron', 'other'),
  ('Chrysler', '300 Hybrid', 'other'),
  ('Chrysler', '300 Electric', 'other'),
  ('Chrysler', '300 Plug-in Hybrid', 'other'),
  ('Chrysler', '300 Touring', 'wagon'),
  ('Dodge', 'Charger', 'coupe'),
  ('Dodge', 'Challenger', 'coupe'),
  ('Dodge', 'Durango', 'other'),
  ('Dodge', 'Hornet', 'other'),
  ('Dodge', 'Journey', 'other'),
  ('Dodge', 'Grand Caravan', 'van'),
  ('Dodge', 'Dart', 'other'),
  ('Dodge', 'Avenger', 'other'),
  ('Dodge', 'Caliber', 'other'),
  ('Dodge', 'Nitro', 'other'),
  ('Dodge', 'Magnum', 'other'),
  ('Dodge', 'Viper', 'other'),
  ('Dodge', 'Stealth', 'other'),
  ('Dodge', 'Intrepid', 'other'),
  ('Dodge', 'Neon', 'other'),
  ('Dodge', 'Ramcharger', 'other'),
  ('Dodge', 'Charger Hybrid', 'coupe'),
  ('Dodge', 'Charger Electric', 'coupe'),
  ('Jeep', 'Wrangler', 'suv'),
  ('Jeep', 'Grand Cherokee', 'suv'),
  ('Jeep', 'Cherokee', 'suv'),
  ('Jeep', 'Compass', 'suv'),
  ('Jeep', 'Renegade', 'suv'),
  ('Jeep', 'Gladiator', 'other'),
  ('Jeep', 'Wagoneer', 'other'),
  ('Jeep', 'Grand Wagoneer', 'other'),
  ('Jeep', 'Commander', 'other'),
  ('Jeep', 'Liberty', 'other'),
  ('Jeep', 'Patriot', 'other'),
  ('Jeep', 'Commando', 'other'),
  ('Jeep', 'CJ-7', 'other'),
  ('Jeep', 'CJ-5', 'other'),
  ('Jeep', 'Avenger', 'other'),
  ('Jeep', 'Recon', 'other'),
  ('Jeep', 'Wrangler Hybrid', 'suv'),
  ('Jeep', 'Wrangler Electric', 'suv'),
  ('Ram', '1500', 'other'),
  ('Ram', '2500', 'other'),
  ('Ram', '3500', 'other'),
  ('Ram', 'ProMaster City', 'other'),
  ('Ram', 'ProMaster', 'other'),
  ('Ram', 'Dakota', 'other'),
  ('Ram', 'C/V Tradesman', 'other'),
  ('Ram', 'Chassis Cab', 'other'),
  ('Ram', 'TRX', 'other'),
  ('Ram', 'Rebel', 'other'),
  ('Ram', 'Laramie', 'other'),
  ('Ram', 'Big Horn', 'other'),
  ('Ram', 'Limited', 'other'),
  ('Ram', 'Longhorn', 'other'),
  ('Ram', '1500 Hybrid', 'other'),
  ('Ram', '1500 Electric', 'other'),
  ('Ram', '1500 Plug-in Hybrid', 'other'),
  ('Ram', '1500 Touring', 'wagon'),
  ('Tesla', 'Model 3', 'sedan'),
  ('Tesla', 'Model Y', 'suv')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
