-- Part 5/9 — Models (Bentley … BYD, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('Bentley', 'Arnage', 'other'),
  ('Bentley', 'Turbo R', 'other'),
  ('Bentley', 'Eight', 'other'),
  ('Bentley', 'Continental R', 'other'),
  ('Bentley', 'Speed Six', 'other'),
  ('Bentley', 'Batur', 'other'),
  ('Bentley', 'Bacalar', 'other'),
  ('Bentley', 'Continental GT Hybrid', 'coupe'),
  ('Bentley', 'Continental GT Electric', 'coupe'),
  ('Bentley', 'Continental GT Plug-in Hybrid', 'coupe'),
  ('Bentley', 'Continental GT Touring', 'coupe'),
  ('Rolls-Royce', 'Phantom', 'sedan'),
  ('Rolls-Royce', 'Ghost', 'sedan'),
  ('Rolls-Royce', 'Wraith', 'sedan'),
  ('Rolls-Royce', 'Dawn', 'sedan'),
  ('Rolls-Royce', 'Cullinan', 'suv'),
  ('Rolls-Royce', 'Spectre', 'other'),
  ('Rolls-Royce', 'Silver Shadow', 'other'),
  ('Rolls-Royce', 'Silver Spirit', 'other'),
  ('Rolls-Royce', 'Corniche', 'other'),
  ('Rolls-Royce', 'Park Ward', 'other'),
  ('Rolls-Royce', 'Silver Seraph', 'other'),
  ('Rolls-Royce', 'Camargue', 'other'),
  ('Rolls-Royce', 'Silver Cloud', 'other'),
  ('Rolls-Royce', 'Boat Tail', 'other'),
  ('Rolls-Royce', 'Phantom Hybrid', 'sedan'),
  ('Rolls-Royce', 'Phantom Electric', 'sedan'),
  ('Rolls-Royce', 'Phantom Plug-in Hybrid', 'sedan'),
  ('Rolls-Royce', 'Phantom Touring', 'wagon'),
  ('Aston Martin', 'DB11', 'coupe'),
  ('Aston Martin', 'DB12', 'other'),
  ('Aston Martin', 'Vantage', 'coupe'),
  ('Aston Martin', 'DBS', 'other'),
  ('Aston Martin', 'DBX', 'suv'),
  ('Aston Martin', 'Valhalla', 'other'),
  ('Aston Martin', 'Valkyrie', 'other'),
  ('Aston Martin', 'Vanquish', 'other'),
  ('Aston Martin', 'Rapide', 'other'),
  ('Aston Martin', 'Virage', 'other'),
  ('Aston Martin', 'DB9', 'other'),
  ('Aston Martin', 'DB7', 'other'),
  ('Aston Martin', 'One-77', 'other'),
  ('Aston Martin', 'Cygnet', 'other'),
  ('Aston Martin', 'Lagonda', 'other'),
  ('Aston Martin', 'Victor', 'other'),
  ('Aston Martin', 'DB11 Hybrid', 'coupe'),
  ('Aston Martin', 'DB11 Electric', 'coupe'),
  ('Jaguar', 'XE', 'other'),
  ('Jaguar', 'XF', 'other'),
  ('Jaguar', 'XJ', 'other'),
  ('Jaguar', 'F-Pace', 'other'),
  ('Jaguar', 'E-Pace', 'other'),
  ('Jaguar', 'I-Pace', 'other'),
  ('Jaguar', 'F-Type', 'coupe'),
  ('Jaguar', 'XK', 'other'),
  ('Jaguar', 'S-Type', 'other'),
  ('Jaguar', 'X-Type', 'other'),
  ('Jaguar', 'XKR', 'other'),
  ('Jaguar', 'XFR', 'other'),
  ('Jaguar', 'Mark 2', 'other'),
  ('Jaguar', 'E-Type', 'other'),
  ('Jaguar', 'XJS', 'other'),
  ('Jaguar', 'XJ220', 'other'),
  ('Jaguar', 'C-X75', 'other'),
  ('Jaguar', 'XE Hybrid', 'other'),
  ('Land Rover', 'Range Rover', 'suv'),
  ('Land Rover', 'Range Rover Sport', 'suv'),
  ('Land Rover', 'Range Rover Velar', 'suv'),
  ('Land Rover', 'Range Rover Evoque', 'suv'),
  ('Land Rover', 'Defender', 'suv'),
  ('Land Rover', 'Discovery', 'suv'),
  ('Land Rover', 'Discovery Sport', 'suv'),
  ('Land Rover', 'Freelander', 'other'),
  ('Land Rover', 'Series III', 'other'),
  ('Land Rover', 'LR2', 'other'),
  ('Land Rover', 'LR3', 'other'),
  ('Land Rover', 'LR4', 'other'),
  ('Land Rover', 'Classic', 'other'),
  ('Land Rover', '130', 'other'),
  ('Land Rover', '110', 'other'),
  ('Land Rover', '90', 'other'),
  ('Land Rover', 'Range Rover Hybrid', 'suv'),
  ('Land Rover', 'Range Rover Electric', 'suv'),
  ('Mini', 'Cooper', 'other'),
  ('Mini', 'Cooper S', 'other'),
  ('Mini', 'Countryman', 'other'),
  ('Mini', 'Clubman', 'other'),
  ('Mini', 'Paceman', 'other'),
  ('Mini', 'Convertible', 'convertible'),
  ('Mini', 'Coupe', 'coupe'),
  ('Mini', 'Roadster', 'convertible'),
  ('Mini', 'John Cooper Works', 'other'),
  ('Mini', 'Electric', 'other'),
  ('Mini', 'Aceman', 'other'),
  ('Mini', 'Cooper SE', 'other'),
  ('Mini', 'One', 'other'),
  ('Mini', 'Hatch', 'hatchback'),
  ('Mini', 'Hardtop', 'other'),
  ('Mini', 'Cooper Hybrid', 'other'),
  ('Mini', 'Cooper Electric', 'other'),
  ('Mini', 'Cooper Plug-in Hybrid', 'other'),
  ('Hyundai', 'Elantra', 'other'),
  ('Hyundai', 'Sonata', 'sedan'),
  ('Hyundai', 'Accent', 'other'),
  ('Hyundai', 'Azera', 'other'),
  ('Hyundai', 'Tucson', 'suv'),
  ('Hyundai', 'Santa Fe', 'suv'),
  ('Hyundai', 'Palisade', 'suv'),
  ('Hyundai', 'Kona', 'suv'),
  ('Hyundai', 'Venue', 'suv'),
  ('Hyundai', 'Ioniq 5', 'suv'),
  ('Hyundai', 'Ioniq 6', 'other'),
  ('Hyundai', 'Ioniq', 'other'),
  ('Hyundai', 'Veloster', 'other'),
  ('Hyundai', 'Genesis Coupe', 'coupe'),
  ('Hyundai', 'Nexo', 'other'),
  ('Hyundai', 'Staria', 'other'),
  ('Hyundai', 'Bayon', 'other'),
  ('Hyundai', 'Creta', 'other'),
  ('Hyundai', 'i10', 'other'),
  ('Hyundai', 'i20', 'hatchback'),
  ('Hyundai', 'i30', 'hatchback'),
  ('Kia', 'Forte', 'other'),
  ('Kia', 'K5', 'sedan'),
  ('Kia', 'Stinger', 'other'),
  ('Kia', 'Soul', 'suv'),
  ('Kia', 'Seltos', 'suv'),
  ('Kia', 'Sportage', 'suv'),
  ('Kia', 'Sorento', 'suv'),
  ('Kia', 'Telluride', 'suv'),
  ('Kia', 'Carnival', 'van'),
  ('Kia', 'Niro', 'other'),
  ('Kia', 'EV6', 'suv'),
  ('Kia', 'EV9', 'suv'),
  ('Kia', 'Rio', 'other'),
  ('Kia', 'Optima', 'other'),
  ('Kia', 'Cadenza', 'other'),
  ('Kia', 'K900', 'other'),
  ('Kia', 'Mohave', 'other'),
  ('Kia', 'Picanto', 'other'),
  ('Kia', 'Cerato', 'other'),
  ('Kia', 'Proceed', 'other'),
  ('Genesis', 'G70', 'other'),
  ('Genesis', 'G80', 'other'),
  ('Genesis', 'G90', 'other'),
  ('Genesis', 'GV60', 'other'),
  ('Genesis', 'GV70', 'other'),
  ('Genesis', 'GV80', 'other'),
  ('Genesis', 'Electrified G80', 'other'),
  ('Genesis', 'Electrified GV70', 'other'),
  ('Genesis', 'X Concept', 'other'),
  ('Genesis', 'Essentia', 'other'),
  ('Genesis', 'Mint', 'other'),
  ('Genesis', 'Neolun', 'other'),
  ('Genesis', 'Coupe Concept', 'coupe'),
  ('Genesis', 'G70 Hybrid', 'other'),
  ('Genesis', 'G70 Electric', 'other'),
  ('Genesis', 'G70 Plug-in Hybrid', 'other'),
  ('Genesis', 'G70 Touring', 'wagon'),
  ('Genesis', 'G70 Sport', 'suv'),
  ('SsangYong', 'Torres', 'other'),
  ('SsangYong', 'Korando', 'other'),
  ('SsangYong', 'Rexton', 'other'),
  ('SsangYong', 'Tivoli', 'other'),
  ('SsangYong', 'Musso', 'other'),
  ('SsangYong', 'Rodius', 'other'),
  ('SsangYong', 'Kyron', 'other'),
  ('SsangYong', 'Actyon', 'other'),
  ('SsangYong', 'Chairman', 'other'),
  ('SsangYong', 'Stavic', 'other'),
  ('SsangYong', 'XLV', 'other'),
  ('SsangYong', 'Korando e-Motion', 'other'),
  ('SsangYong', 'Torres EVX', 'other'),
  ('SsangYong', 'Torres Hybrid', 'other'),
  ('SsangYong', 'Torres Electric', 'other'),
  ('SsangYong', 'Torres Plug-in Hybrid', 'other'),
  ('SsangYong', 'Torres Touring', 'wagon'),
  ('SsangYong', 'Torres Sport', 'suv'),
  ('Skoda', 'Octavia', 'other'),
  ('Skoda', 'Superb', 'other'),
  ('Skoda', 'Fabia', 'other'),
  ('Skoda', 'Scala', 'other'),
  ('Skoda', 'Kamiq', 'other'),
  ('Skoda', 'Karoq', 'suv'),
  ('Skoda', 'Kodiaq', 'suv'),
  ('Skoda', 'Enyaq', 'suv'),
  ('Skoda', 'Rapid', 'other'),
  ('Skoda', 'Yeti', 'other'),
  ('Skoda', 'Roomster', 'other'),
  ('Skoda', 'Citigo', 'other'),
  ('Skoda', 'Felicia', 'other'),
  ('Skoda', 'Favorit', 'other'),
  ('Skoda', 'Kushaq', 'other'),
  ('Skoda', 'Slavia', 'other'),
  ('Skoda', 'Monte Carlo', 'other'),
  ('Skoda', 'Octavia Hybrid', 'other'),
  ('SEAT', 'Ibiza', 'other'),
  ('SEAT', 'Leon', 'other'),
  ('SEAT', 'Arona', 'other'),
  ('SEAT', 'Ateca', 'other'),
  ('SEAT', 'Tarraco', 'other'),
  ('SEAT', 'Alhambra', 'van'),
  ('SEAT', 'Toledo', 'other'),
  ('SEAT', 'Cordoba', 'other'),
  ('SEAT', 'Altea', 'other'),
  ('SEAT', 'Mii', 'other'),
  ('SEAT', 'Exeo', 'other'),
  ('SEAT', 'Marbella', 'other'),
  ('SEAT', 'Malaga', 'other'),
  ('SEAT', 'Ronda', 'other'),
  ('SEAT', 'Ibiza Hybrid', 'other'),
  ('SEAT', 'Ibiza Electric', 'other'),
  ('SEAT', 'Ibiza Plug-in Hybrid', 'other'),
  ('SEAT', 'Ibiza Touring', 'wagon'),
  ('Cupra', 'Formentor', 'other'),
  ('Cupra', 'Leon', 'other'),
  ('Cupra', 'Born', 'other'),
  ('Cupra', 'Ateca', 'other'),
  ('Cupra', 'Tavascan', 'other'),
  ('Cupra', 'Terramar', 'other'),
  ('Cupra', 'Urban Rebel', 'other'),
  ('Cupra', 'Raval', 'other'),
  ('Cupra', 'Ibiza', 'other'),
  ('Cupra', 'DarkRebel', 'other'),
  ('Cupra', 'TCR', 'other'),
  ('Cupra', 'e-Racer', 'other'),
  ('Cupra', 'Formentor VZ5', 'other'),
  ('Cupra', 'Formentor Hybrid', 'other'),
  ('Cupra', 'Formentor Electric', 'other'),
  ('Cupra', 'Formentor Plug-in Hybrid', 'other'),
  ('Cupra', 'Formentor Touring', 'wagon'),
  ('Cupra', 'Formentor Sport', 'suv'),
  ('BYD', 'Han', 'other'),
  ('BYD', 'Tang', 'other'),
  ('BYD', 'Song', 'other'),
  ('BYD', 'Song Plus', 'other'),
  ('BYD', 'Yuan', 'other'),
  ('BYD', 'Yuan Plus', 'other'),
  ('BYD', 'Seal', 'other'),
  ('BYD', 'Dolphin', 'other'),
  ('BYD', 'Atto 3', 'other'),
  ('BYD', 'Seagull', 'other'),
  ('BYD', 'Qin', 'other'),
  ('BYD', 'Destroyer 05', 'other'),
  ('BYD', 'Frigate 07', 'other'),
  ('BYD', 'Shark', 'other'),
  ('BYD', 'Yangwang U8', 'other'),
  ('BYD', 'Yangwang U9', 'other'),
  ('BYD', 'Han Hybrid', 'other'),
  ('BYD', 'Han Electric', 'other')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
