-- Part 8/9 — Models (MAN TGE … Yutong, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('MAN TGE', 'TGE L2H2', 'minibus'),
  ('MAN TGE', 'TGE L3H2', 'minibus'),
  ('MAN TGE', 'TGE Shuttle', 'minibus'),
  ('MAN TGE', 'TGE School', 'minibus'),
  ('MAN TGE', 'TGE City', 'minibus'),
  ('MAN TGE', 'TGE Wheelchair', 'minibus'),
  ('MAN TGE', 'TGE Commuter', 'minibus'),
  ('MAN TGE', 'TGE 3140', 'minibus'),
  ('MAN TGE', 'TGE 3180', 'minibus'),
  ('MAN TGE', 'TGE 3200', 'minibus'),
  ('MAN TGE', 'TGE Minibus Hybrid', 'minibus'),
  ('MAN TGE', 'TGE Minibus Electric', 'minibus'),
  ('MAN TGE', 'TGE Minibus Plug-in Hybrid', 'minibus'),
  ('MAN TGE', 'TGE Minibus Touring', 'minibus'),
  ('MAN TGE', 'TGE Minibus Sport', 'minibus'),
  ('MAN TGE', 'TGE Minibus Limited', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus', 'minibus'),
  ('Toyota Commuter', 'Coaster', 'minibus'),
  ('Toyota Commuter', 'Coaster B50', 'minibus'),
  ('Toyota Commuter', 'Coaster Gold', 'minibus'),
  ('Toyota Commuter', 'Quantum', 'minibus'),
  ('Toyota Commuter', 'Ses''fikile', 'minibus'),
  ('Toyota Commuter', 'Ventury 16', 'minibus'),
  ('Toyota Commuter', 'HiAce 14 Seater', 'minibus'),
  ('Toyota Commuter', 'HiAce 15 Seater', 'minibus'),
  ('Toyota Commuter', 'Coaster School', 'minibus'),
  ('Toyota Commuter', 'Coaster Wheelchair', 'minibus'),
  ('Toyota Commuter', 'Coaster Long', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Hybrid', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Electric', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Plug-in Hybrid', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Touring', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Sport', 'minibus'),
  ('Toyota Commuter', 'HiAce Commuter Bus Limited', 'minibus'),
  ('LDV', 'Deliver 9 Minibus', 'minibus'),
  ('LDV', 'Deliver 7 Minibus', 'minibus'),
  ('LDV', 'V80 Minibus', 'minibus'),
  ('LDV', 'G10', 'minibus'),
  ('LDV', 'G10 Plus', 'minibus'),
  ('LDV', 'Deliver 9 Shuttle', 'minibus'),
  ('LDV', 'Deliver 9 School', 'minibus'),
  ('LDV', 'Deliver 9 Commuter', 'minibus'),
  ('LDV', 'V80 Commuter', 'minibus'),
  ('LDV', 'Mifa 9', 'minibus'),
  ('LDV', 'Mifa 7', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Hybrid', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Electric', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Plug-in Hybrid', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Touring', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Sport', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Limited', 'minibus'),
  ('LDV', 'Deliver 9 Minibus Premium', 'minibus'),
  ('Mercedes-Benz Coaches', 'Tourismo', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo R', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo M', 'coach'),
  ('Mercedes-Benz Coaches', 'Travego', 'coach'),
  ('Mercedes-Benz Coaches', 'Travego M', 'coach'),
  ('Mercedes-Benz Coaches', 'Travego L', 'coach'),
  ('Mercedes-Benz Coaches', 'Intouro', 'coach'),
  ('Mercedes-Benz Coaches', 'Intouro K', 'coach'),
  ('Mercedes-Benz Coaches', 'Intouro M', 'coach'),
  ('Mercedes-Benz Coaches', 'Setra MultiClass', 'coach'),
  ('Mercedes-Benz Coaches', 'Citaro', 'coach'),
  ('Mercedes-Benz Coaches', 'Citaro G', 'coach'),
  ('Mercedes-Benz Coaches', 'Citaro U', 'coach'),
  ('Mercedes-Benz Coaches', 'eCitaro', 'coach'),
  ('Mercedes-Benz Coaches', 'Conecto', 'coach'),
  ('Mercedes-Benz Coaches', 'Capacito', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo E', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo K', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo Hybrid', 'coach'),
  ('Mercedes-Benz Coaches', 'Tourismo Electric', 'coach'),
  ('Volvo Coaches', '9700', 'coach'),
  ('Volvo Coaches', '9900', 'coach'),
  ('Volvo Coaches', '8900', 'other'),
  ('Volvo Coaches', '7900', 'other'),
  ('Volvo Coaches', 'B11R', 'other'),
  ('Volvo Coaches', 'B8R', 'other'),
  ('Volvo Coaches', 'B13R', 'other'),
  ('Volvo Coaches', '9700 DD', 'coach'),
  ('Volvo Coaches', '9900 DD', 'coach'),
  ('Volvo Coaches', '9700 B', 'coach'),
  ('Volvo Coaches', '7900 Electric', 'other'),
  ('Volvo Coaches', '7900 Hybrid', 'other'),
  ('Volvo Coaches', 'B7R', 'other'),
  ('Volvo Coaches', 'B9R', 'other'),
  ('Volvo Coaches', 'B12M', 'other'),
  ('Volvo Coaches', 'B12B', 'other'),
  ('Volvo Coaches', '8700', 'other'),
  ('Volvo Coaches', '9400', 'other'),
  ('Scania', 'Touring', 'wagon'),
  ('Scania', 'Touring HD', 'wagon'),
  ('Scania', 'Interlink', 'other'),
  ('Scania', 'Citywide', 'other'),
  ('Scania', 'Fencer', 'other'),
  ('Scania', 'Marco Polo', 'van'),
  ('Scania', 'Irizar i6 Scania', 'coach'),
  ('Scania', 'K-series', 'other'),
  ('Scania', 'N-series', 'other'),
  ('Scania', 'F-series', 'other'),
  ('Scania', 'H-series', 'other'),
  ('Scania', 'L-series', 'other'),
  ('Scania', 'OmniExpress', 'other'),
  ('Scania', 'OmniLink', 'other'),
  ('Scania', 'OmniCity', 'other'),
  ('Scania', 'Metrolink', 'other'),
  ('Scania', 'Touring Hybrid', 'wagon'),
  ('Scania', 'Touring Electric', 'wagon'),
  ('MAN Coaches', 'Lion''s Coach', 'coach'),
  ('MAN Coaches', 'Lion''s Coach E', 'coach'),
  ('MAN Coaches', 'Lion''s Intercity', 'other'),
  ('MAN Coaches', 'Lion''s City', 'other'),
  ('MAN Coaches', 'Lion''s City E', 'other'),
  ('MAN Coaches', 'Lion''s Regio', 'other'),
  ('MAN Coaches', 'Fortuna', 'other'),
  ('MAN Coaches', 'Lion''s Coach C', 'coach'),
  ('MAN Coaches', 'Lion''s Coach L', 'coach'),
  ('MAN Coaches', 'Lion''s Coach LE', 'coach'),
  ('MAN Coaches', 'Lion''s Coach DD', 'coach'),
  ('MAN Coaches', 'Neoplan Skyliner', 'coach'),
  ('MAN Coaches', 'Neoplan Tourliner', 'coach'),
  ('MAN Coaches', 'Neoplan Cityliner', 'coach'),
  ('MAN Coaches', 'Lion''s Coach Hybrid', 'coach'),
  ('MAN Coaches', 'Lion''s Coach Electric', 'coach'),
  ('MAN Coaches', 'Lion''s Coach Plug-in Hybrid', 'coach'),
  ('MAN Coaches', 'Lion''s Coach Touring', 'coach'),
  ('Setra', 'S 515 HD', 'other'),
  ('Setra', 'S 516 HD', 'other'),
  ('Setra', 'S 517 HD', 'other'),
  ('Setra', 'S 531 DT', 'other'),
  ('Setra', 'S 531 DT-2', 'other'),
  ('Setra', 'S 417 TC', 'other'),
  ('Setra', 'S 431 DT', 'other'),
  ('Setra', 'ComfortClass', 'other'),
  ('Setra', 'TopClass', 'other'),
  ('Setra', 'MultiClass', 'other'),
  ('Setra', 'S 415 NF', 'other'),
  ('Setra', 'S 416 NF', 'other'),
  ('Setra', 'S 515 LE', 'other'),
  ('Setra', 'S 516 LE', 'other'),
  ('Setra', 'S 515 HD Hybrid', 'other'),
  ('Setra', 'S 515 HD Electric', 'other'),
  ('Setra', 'S 515 HD Plug-in Hybrid', 'other'),
  ('Setra', 'S 515 HD Touring', 'wagon'),
  ('Neoplan', 'Skyliner', 'other'),
  ('Neoplan', 'Tourliner', 'other'),
  ('Neoplan', 'Cityliner', 'other'),
  ('Neoplan', 'Starliner', 'other'),
  ('Neoplan', 'Jetliner', 'other'),
  ('Neoplan', 'Centroliner', 'other'),
  ('Neoplan', 'Metroliner', 'other'),
  ('Neoplan', 'Spaceliner', 'other'),
  ('Neoplan', 'Megaliner', 'other'),
  ('Neoplan', 'Euroliner', 'other'),
  ('Neoplan', 'Transliner', 'other'),
  ('Neoplan', 'Skyliner L', 'other'),
  ('Neoplan', 'Tourliner G', 'other'),
  ('Neoplan', 'Cityliner C', 'other'),
  ('Neoplan', 'Skyliner Hybrid', 'other'),
  ('Neoplan', 'Skyliner Electric', 'other'),
  ('Neoplan', 'Skyliner Plug-in Hybrid', 'other'),
  ('Neoplan', 'Skyliner Touring', 'wagon'),
  ('Van Hool', 'T9', 'other'),
  ('Van Hool', 'T8', 'other'),
  ('Van Hool', 'A9', 'other'),
  ('Van Hool', 'A330', 'other'),
  ('Van Hool', 'CX45', 'other'),
  ('Van Hool', 'CX35', 'other'),
  ('Van Hool', 'ExquiCity', 'other'),
  ('Van Hool', 'New A330', 'other'),
  ('Van Hool', 'New T9', 'other'),
  ('Van Hool', 'Altano', 'other'),
  ('Van Hool', 'Astromega', 'other'),
  ('Van Hool', 'C2045', 'other'),
  ('Van Hool', 'T915', 'other'),
  ('Van Hool', 'A308', 'other'),
  ('Van Hool', 'ExquiCity 18', 'other'),
  ('Van Hool', 'ExquiCity 24', 'other'),
  ('Van Hool', 'T9 Hybrid', 'other'),
  ('Van Hool', 'T9 Electric', 'other'),
  ('Irizar', 'i6', 'coach'),
  ('Irizar', 'i6S', 'other'),
  ('Irizar', 'i8', 'coach'),
  ('Irizar', 'i4', 'other'),
  ('Irizar', 'i3', 'other'),
  ('Irizar', 'ie', 'other'),
  ('Irizar', 'ie tram', 'other'),
  ('Irizar', 'Century', 'other'),
  ('Irizar', 'InterCentury', 'other'),
  ('Irizar', 'PB', 'other'),
  ('Irizar', 'Scania K i6', 'coach'),
  ('Irizar', 'Volvo B i8', 'coach'),
  ('Irizar', 'i6Efficient', 'other'),
  ('Irizar', 'i8Efficient', 'other'),
  ('Irizar', 'i4Efficient', 'other'),
  ('Irizar', 'i6 Hybrid', 'coach'),
  ('Irizar', 'i6 Electric', 'coach'),
  ('Irizar', 'i6 Plug-in Hybrid', 'coach'),
  ('Prevost', 'H3-45', 'other'),
  ('Prevost', 'X3-45', 'suv'),
  ('Prevost', 'X3-45 VIP', 'suv'),
  ('Prevost', 'H3-41', 'other'),
  ('Prevost', 'X3-41', 'suv'),
  ('Prevost', 'X3-41 VIP', 'suv'),
  ('Prevost', 'H3-45 VIP', 'other'),
  ('Prevost', 'X3-45 Commuter', 'suv'),
  ('Prevost', 'H3-45 Commuter', 'other'),
  ('Prevost', 'X3-45 Entertainer', 'suv'),
  ('Prevost', 'H3-45 Entertainer', 'other'),
  ('Prevost', 'Liberty', 'other'),
  ('Prevost', 'Marathon', 'other'),
  ('Prevost', 'H3-45 Hybrid', 'other'),
  ('Prevost', 'H3-45 Electric', 'other'),
  ('Prevost', 'H3-45 Plug-in Hybrid', 'other'),
  ('Prevost', 'H3-45 Touring', 'wagon'),
  ('Prevost', 'H3-45 Sport', 'suv'),
  ('MCI', 'J4500', 'coach'),
  ('MCI', 'D4505', 'other'),
  ('MCI', 'D4500', 'other'),
  ('MCI', 'E4500', 'other'),
  ('MCI', 'G4500', 'other'),
  ('MCI', 'D4005', 'other'),
  ('MCI', 'D4000', 'other'),
  ('MCI', 'J3500', 'other'),
  ('MCI', 'D3500', 'other'),
  ('MCI', 'Commuter Coach', 'coach'),
  ('MCI', 'Entertainer Coach', 'coach'),
  ('MCI', 'Luxury Coach', 'coach'),
  ('MCI', 'Champion', 'other'),
  ('MCI', 'J4500 Hybrid', 'coach'),
  ('MCI', 'J4500 Electric', 'coach'),
  ('MCI', 'J4500 Plug-in Hybrid', 'coach'),
  ('MCI', 'J4500 Touring', 'coach'),
  ('MCI', 'J4500 Sport', 'coach'),
  ('Yutong', 'ZK6128', 'other'),
  ('Yutong', 'ZK6126', 'other'),
  ('Yutong', 'ZK6119', 'other'),
  ('Yutong', 'ZK6908', 'other'),
  ('Yutong', 'ZK6122', 'other'),
  ('Yutong', 'ZK6120', 'other'),
  ('Yutong', 'ZK6125', 'other'),
  ('Yutong', 'ZK6127', 'other'),
  ('Yutong', 'ZK6137', 'other'),
  ('Yutong', 'ZK6147', 'other'),
  ('Yutong', 'T12', 'other'),
  ('Yutong', 'T15', 'other'),
  ('Yutong', 'C12', 'other'),
  ('Yutong', 'C13', 'other'),
  ('Yutong', 'E12', 'other'),
  ('Yutong', 'E15', 'other')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
