-- Part 9/9 — Models (Yutong … Lincoln Special, 200 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('Yutong', 'U12', 'other'),
  ('Yutong', 'U13', 'other'),
  ('King Long', 'XMQ6127', 'other'),
  ('King Long', 'XMQ6129', 'other'),
  ('King Long', 'XMQ6125', 'other'),
  ('King Long', 'XMQ6101', 'other'),
  ('King Long', 'XMQ6905', 'other'),
  ('King Long', 'XMQ6120', 'other'),
  ('King Long', 'XMQ6119', 'other'),
  ('King Long', 'XMQ6122', 'other'),
  ('King Long', 'XMQ6130', 'other'),
  ('King Long', 'XMQ6140', 'other'),
  ('King Long', 'Golden Dragon', 'other'),
  ('King Long', 'XML6127', 'other'),
  ('King Long', 'XML6129', 'other'),
  ('King Long', 'XML6905', 'other'),
  ('King Long', 'XMQ6127 Hybrid', 'other'),
  ('King Long', 'XMQ6127 Electric', 'other'),
  ('King Long', 'XMQ6127 Plug-in Hybrid', 'other'),
  ('King Long', 'XMQ6127 Touring', 'wagon'),
  ('BYD Coaches', 'K9', 'other'),
  ('BYD Coaches', 'K8', 'other'),
  ('BYD Coaches', 'K7', 'other'),
  ('BYD Coaches', 'K11', 'other'),
  ('BYD Coaches', 'K12', 'other'),
  ('BYD Coaches', 'C8', 'other'),
  ('BYD Coaches', 'C9', 'other'),
  ('BYD Coaches', 'C10', 'other'),
  ('BYD Coaches', 'C12', 'other'),
  ('BYD Coaches', 'B12', 'other'),
  ('BYD Coaches', 'B13', 'other'),
  ('BYD Coaches', 'B18', 'other'),
  ('BYD Coaches', 'B70', 'other'),
  ('BYD Coaches', 'B80', 'other'),
  ('BYD Coaches', 'B12A', 'other'),
  ('BYD Coaches', 'B12B', 'other'),
  ('BYD Coaches', 'K9UD', 'other'),
  ('BYD Coaches', 'K9A', 'other'),
  ('Solaris', 'Urbino 12', 'other'),
  ('Solaris', 'Urbino 18', 'other'),
  ('Solaris', 'Urbino 15', 'other'),
  ('Solaris', 'Urbino 9', 'other'),
  ('Solaris', 'Urbino Electric', 'other'),
  ('Solaris', 'Urbino Hybrid', 'other'),
  ('Solaris', 'InterUrbino', 'other'),
  ('Solaris', 'InterUrbino 12', 'other'),
  ('Solaris', 'InterUrbino 13', 'other'),
  ('Solaris', 'Vacanza', 'other'),
  ('Solaris', 'Alpino', 'other'),
  ('Solaris', 'Trollino', 'other'),
  ('Solaris', 'MetroStyle', 'other'),
  ('Solaris', 'i3 Electric', 'other'),
  ('Solaris', 'Urbino 12 Hybrid', 'other'),
  ('Solaris', 'Urbino 12 Electric', 'other'),
  ('Solaris', 'Urbino 12 Plug-in Hybrid', 'other'),
  ('Solaris', 'Urbino 12 Touring', 'wagon'),
  ('Temsa', 'Safari HD', 'other'),
  ('Temsa', 'Safari MD', 'other'),
  ('Temsa', 'Safari Commuter', 'other'),
  ('Temsa', 'Maraton', 'other'),
  ('Temsa', 'Avenue', 'other'),
  ('Temsa', 'Prestij', 'other'),
  ('Temsa', 'LD SB Plus', 'other'),
  ('Temsa', 'HD 12', 'other'),
  ('Temsa', 'HD 13', 'other'),
  ('Temsa', 'MD 9', 'other'),
  ('Temsa', 'MD 12', 'other'),
  ('Temsa', 'Safari RD', 'other'),
  ('Temsa', 'Safari XL', 'other'),
  ('Temsa', 'Safari HD Hybrid', 'other'),
  ('Temsa', 'Safari HD Electric', 'other'),
  ('Temsa', 'Safari HD Plug-in Hybrid', 'other'),
  ('Temsa', 'Safari HD Touring', 'wagon'),
  ('Temsa', 'Safari HD Sport', 'suv'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance', 'van'),
  ('Mercedes-Benz Special', 'Vito Ambulance', 'van'),
  ('Mercedes-Benz Special', 'G-Class Armored', 'suv'),
  ('Mercedes-Benz Special', 'S-Class Armored', 'sedan'),
  ('Mercedes-Benz Special', 'Maybach Pullman', 'sedan'),
  ('Mercedes-Benz Special', 'Sprinter Prisoner Transport', 'van'),
  ('Mercedes-Benz Special', 'Unimog', 'other'),
  ('Mercedes-Benz Special', 'Zetros', 'other'),
  ('Mercedes-Benz Special', 'Actros Special', 'other'),
  ('Mercedes-Benz Special', 'Atego Special', 'other'),
  ('Mercedes-Benz Special', 'Sprinter Refrigerated', 'van'),
  ('Mercedes-Benz Special', 'V-Class VIP', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Limousine', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance Hybrid', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance Electric', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance Plug-in Hybrid', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance Touring', 'van'),
  ('Mercedes-Benz Special', 'Sprinter Ambulance Sport', 'van'),
  ('Ford Special', 'Transit Ambulance', 'van'),
  ('Ford Special', 'Transit Prisoner Transport', 'van'),
  ('Ford Special', 'F-550 Ambulance', 'other'),
  ('Ford Special', 'E-Series Ambulance', 'other'),
  ('Ford Special', 'Transit Limousine', 'van'),
  ('Ford Special', 'Mustang Parade Car', 'coupe'),
  ('Ford Special', 'Transit Refrigerated', 'van'),
  ('Ford Special', 'Transit Mobile Clinic', 'van'),
  ('Ford Special', 'Bronco First Responder', 'suv'),
  ('Ford Special', 'F-650 Chassis Cab', 'other'),
  ('Ford Special', 'Transit Ambulance Hybrid', 'van'),
  ('Ford Special', 'Transit Ambulance Electric', 'van'),
  ('Ford Special', 'Transit Ambulance Plug-in Hybrid', 'van'),
  ('Ford Special', 'Transit Ambulance Touring', 'van'),
  ('Ford Special', 'Transit Ambulance Sport', 'van'),
  ('Ford Special', 'Transit Ambulance Limited', 'van'),
  ('Ford Special', 'Transit Ambulance Premium', 'van'),
  ('Ford Special', 'Transit Ambulance Executive', 'van'),
  ('Toyota Special', 'Land Cruiser Armored', 'other'),
  ('Toyota Special', 'HiAce Ambulance', 'van'),
  ('Toyota Special', 'Coaster Mobile Clinic', 'other'),
  ('Toyota Special', 'Alphard Executive', 'other'),
  ('Toyota Special', 'Mirai Police', 'other'),
  ('Toyota Special', 'Tundra Fire Truck', 'pickup'),
  ('Toyota Special', 'Proace Ambulance', 'other'),
  ('Toyota Special', 'Hilux Emergency', 'pickup'),
  ('Toyota Special', 'Land Cruiser Fire', 'other'),
  ('Toyota Special', 'Coaster Wheelchair', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Hybrid', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Electric', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Plug-in Hybrid', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Touring', 'wagon'),
  ('Toyota Special', 'Land Cruiser Armored Sport', 'suv'),
  ('Toyota Special', 'Land Cruiser Armored Limited', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Premium', 'other'),
  ('Toyota Special', 'Land Cruiser Armored Executive', 'other'),
  ('Rolls-Royce Special', 'Phantom Extended', 'sedan'),
  ('Rolls-Royce Special', 'Ghost Extended', 'sedan'),
  ('Rolls-Royce Special', 'Cullinan Black Badge', 'suv'),
  ('Rolls-Royce Special', 'Phantom Limousine', 'sedan'),
  ('Rolls-Royce Special', 'Ghost Armored', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Drophead Parade', 'sedan'),
  ('Rolls-Royce Special', 'Spectre Chauffeur', 'other'),
  ('Rolls-Royce Special', 'Wraith Black Badge', 'sedan'),
  ('Rolls-Royce Special', 'Dawn Black Badge', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Hybrid', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Electric', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Plug-in Hybrid', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Touring', 'wagon'),
  ('Rolls-Royce Special', 'Phantom Extended Sport', 'suv'),
  ('Rolls-Royce Special', 'Phantom Extended Limited', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Premium', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended Executive', 'sedan'),
  ('Rolls-Royce Special', 'Phantom Extended SE', 'sedan'),
  ('BMW Special', '7 Series Protection', 'sedan'),
  ('BMW Special', 'X5 Protection', 'suv'),
  ('BMW Special', 'X7 Protection', 'suv'),
  ('BMW Special', 'i7 Protection', 'other'),
  ('BMW Special', '5 Series Police', 'sedan'),
  ('BMW Special', 'M5 Emergency', 'other'),
  ('BMW Special', 'X5 Ambulance', 'suv'),
  ('BMW Special', '7 Series Limousine', 'sedan'),
  ('BMW Special', 'iX M60 Emergency', 'other'),
  ('BMW Special', '7 Series Protection Hybrid', 'sedan'),
  ('BMW Special', '7 Series Protection Electric', 'sedan'),
  ('BMW Special', '7 Series Protection Plug-in Hybrid', 'sedan'),
  ('BMW Special', '7 Series Protection Touring', 'wagon'),
  ('BMW Special', '7 Series Protection Sport', 'suv'),
  ('BMW Special', '7 Series Protection Limited', 'sedan'),
  ('BMW Special', '7 Series Protection Premium', 'sedan'),
  ('BMW Special', '7 Series Protection Executive', 'sedan'),
  ('BMW Special', '7 Series Protection SE', 'sedan'),
  ('Cadillac Special', 'Escalade Stretch', 'suv'),
  ('Cadillac Special', 'Escalade ESV Limousine', 'suv'),
  ('Cadillac Special', 'XTS Limousine', 'sedan'),
  ('Cadillac Special', 'Fleetwood Hearse', 'other'),
  ('Cadillac Special', 'Escalade Armored', 'suv'),
  ('Cadillac Special', 'CT5-V Blackwing Parade', 'sedan'),
  ('Cadillac Special', 'Presidential State Car', 'other'),
  ('Cadillac Special', 'Escalade Mobile Command', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Hybrid', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Electric', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Plug-in Hybrid', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Touring', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Sport', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Limited', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Premium', 'suv'),
  ('Cadillac Special', 'Escalade Stretch Executive', 'suv'),
  ('Cadillac Special', 'Escalade Stretch SE', 'suv'),
  ('Cadillac Special', 'Escalade Stretch XLE', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine', 'suv'),
  ('Lincoln Special', 'Continental Coach Door', 'coach'),
  ('Lincoln Special', 'Town Car Limousine', 'sedan'),
  ('Lincoln Special', 'Navigator Armored', 'suv'),
  ('Lincoln Special', 'MKT Hearse', 'other'),
  ('Lincoln Special', 'Navigator Presidential', 'suv'),
  ('Lincoln Special', 'Blackwood Special', 'other'),
  ('Lincoln Special', 'Aviator Limousine', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Hybrid', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Electric', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Plug-in Hybrid', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Touring', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Sport', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Limited', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Premium', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine Executive', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine SE', 'suv'),
  ('Lincoln Special', 'Navigator L Limousine XLE', 'suv')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;

COMMIT;

