-- Part 7/9 — Models (Peugeot Traveller … MAN TGE, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('Peugeot Traveller', 'Rifter Long', 'van'),
  ('Peugeot Traveller', 'Partner Combi', 'van'),
  ('Peugeot Traveller', 'Traveller Hybrid', 'van'),
  ('Peugeot Traveller', 'Traveller Electric', 'van'),
  ('Peugeot Traveller', 'Traveller Plug-in Hybrid', 'van'),
  ('Peugeot Traveller', 'Traveller Touring', 'van'),
  ('Peugeot Traveller', 'Traveller Sport', 'van'),
  ('Peugeot Traveller', 'Traveller Limited', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer', 'van'),
  ('Citroen SpaceTourer', 'Berlingo Multispace', 'van'),
  ('Citroen SpaceTourer', 'Jumpy SpaceTourer', 'van'),
  ('Citroen SpaceTourer', 'C4 SpaceTourer', 'van'),
  ('Citroen SpaceTourer', 'C8', 'van'),
  ('Citroen SpaceTourer', 'Xsara Picasso', 'van'),
  ('Citroen SpaceTourer', 'C3 Picasso', 'van'),
  ('Citroen SpaceTourer', 'Dispatch Combi', 'van'),
  ('Citroen SpaceTourer', 'e-SpaceTourer', 'van'),
  ('Citroen SpaceTourer', 'Berlingo XL', 'van'),
  ('Citroen SpaceTourer', 'Spacetourer Business', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Hybrid', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Electric', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Plug-in Hybrid', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Touring', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Sport', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Limited', 'van'),
  ('Citroen SpaceTourer', 'SpaceTourer Premium', 'van'),
  ('Opel Zafira Life', 'Zafira Life', 'van'),
  ('Opel Zafira Life', 'Combo Life', 'van'),
  ('Opel Zafira Life', 'Vivaro Life', 'van'),
  ('Opel Zafira Life', 'Meriva', 'van'),
  ('Opel Zafira Life', 'Sintra', 'van'),
  ('Opel Zafira Life', 'Zafira', 'van'),
  ('Opel Zafira Life', 'Zafira Tourer', 'van'),
  ('Opel Zafira Life', 'Combo Tour', 'van'),
  ('Opel Zafira Life', 'Vivaro Combi', 'van'),
  ('Opel Zafira Life', 'Mokka-e MPV', 'van'),
  ('Opel Zafira Life', 'Frontera MPV', 'van'),
  ('Opel Zafira Life', 'Zafira Life Hybrid', 'van'),
  ('Opel Zafira Life', 'Zafira Life Electric', 'van'),
  ('Opel Zafira Life', 'Zafira Life Plug-in Hybrid', 'van'),
  ('Opel Zafira Life', 'Zafira Life Touring', 'van'),
  ('Opel Zafira Life', 'Zafira Life Sport', 'van'),
  ('Opel Zafira Life', 'Zafira Life Limited', 'van'),
  ('Opel Zafira Life', 'Zafira Life Premium', 'van'),
  ('Fiat Ulysse', 'Doblo MPV', 'van'),
  ('Fiat Ulysse', 'Ulysse', 'van'),
  ('Fiat Ulysse', 'Multipla', 'van'),
  ('Fiat Ulysse', 'Scudo Panorama', 'van'),
  ('Fiat Ulysse', 'Talento Panorama', 'van'),
  ('Fiat Ulysse', '500L Living', 'van'),
  ('Fiat Ulysse', 'Doblo Combi', 'van'),
  ('Fiat Ulysse', 'Doblo XL', 'van'),
  ('Fiat Ulysse', 'e-Doblo', 'van'),
  ('Fiat Ulysse', 'Scudo Combi', 'van'),
  ('Fiat Ulysse', 'Ulysse Hybrid', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Hybrid', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Electric', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Plug-in Hybrid', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Touring', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Sport', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Limited', 'van'),
  ('Fiat Ulysse', 'Doblo MPV Premium', 'van'),
  ('Toyota HiAce', 'HiAce Commuter', 'van'),
  ('Toyota HiAce', 'HiAce GL', 'van'),
  ('Toyota HiAce', 'HiAce Super GL', 'van'),
  ('Toyota HiAce', 'HiAce Regius', 'van'),
  ('Toyota HiAce', 'HiAce Grandia', 'van'),
  ('Toyota HiAce', 'HiAce LWB', 'van'),
  ('Toyota HiAce', 'HiAce SLWB', 'van'),
  ('Toyota HiAce', 'HiAce Crew Van', 'van'),
  ('Toyota HiAce', 'HiAce Ambulance', 'van'),
  ('Toyota HiAce', 'HiAce Wheelchair', 'van'),
  ('Toyota HiAce', 'Quantum', 'van'),
  ('Toyota HiAce', 'Ventury', 'van'),
  ('Toyota HiAce', 'Ses''fikile', 'van'),
  ('Toyota HiAce', 'HiAce Siyaya', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Hybrid', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Electric', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Plug-in Hybrid', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Touring', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Sport', 'van'),
  ('Toyota HiAce', 'HiAce Commuter Limited', 'van'),
  ('Mercedes-Benz Sprinter', 'Sprinter 311', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 314', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 316', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 319', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 324', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter Crew', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter Shuttle', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter Minibus', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter City', 'minibus'),
  ('Mercedes-Benz Sprinter', 'eSprinter', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter Transfer', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter Mobility', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 417', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 519', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter L2H2', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter L3H2', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter L4H3', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 311 Hybrid', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 311 Electric', 'minibus'),
  ('Mercedes-Benz Sprinter', 'Sprinter 311 Plug-in Hybrid', 'minibus'),
  ('Ford Transit', 'Transit 350', 'minibus'),
  ('Ford Transit', 'Transit 410', 'minibus'),
  ('Ford Transit', 'Transit Minibus', 'minibus'),
  ('Ford Transit', 'Transit Shuttle', 'minibus'),
  ('Ford Transit', 'Transit Crew', 'minibus'),
  ('Ford Transit', 'Transit L3H2', 'minibus'),
  ('Ford Transit', 'Transit L4H3', 'minibus'),
  ('Ford Transit', 'Transit Custom Minibus', 'minibus'),
  ('Ford Transit', 'E-Transit Minibus', 'minibus'),
  ('Ford Transit', 'Transit 460', 'minibus'),
  ('Ford Transit', 'Transit 470', 'minibus'),
  ('Ford Transit', 'Transit Trail', 'minibus'),
  ('Ford Transit', 'Transit Connect Minibus', 'minibus'),
  ('Ford Transit', 'Transit Passenger', 'minibus'),
  ('Ford Transit', 'Transit 350 Hybrid', 'minibus'),
  ('Ford Transit', 'Transit 350 Electric', 'minibus'),
  ('Ford Transit', 'Transit 350 Plug-in Hybrid', 'minibus'),
  ('Ford Transit', 'Transit 350 Touring', 'minibus'),
  ('Ford Transit', 'Transit 350 Sport', 'minibus'),
  ('Ford Transit', 'Transit 350 Limited', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Kombi', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Shuttle', 'minibus'),
  ('Volkswagen Crafter', 'Crafter L3H2', 'minibus'),
  ('Volkswagen Crafter', 'Crafter L4H3', 'minibus'),
  ('Volkswagen Crafter', 'Crafter 35', 'minibus'),
  ('Volkswagen Crafter', 'Crafter 50', 'minibus'),
  ('Volkswagen Crafter', 'Crafter 55', 'minibus'),
  ('Volkswagen Crafter', 'e-Crafter Shuttle', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Transfer', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Mobility', 'minibus'),
  ('Volkswagen Crafter', 'Crafter School', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Commuter', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus Hybrid', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus Electric', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus Plug-in Hybrid', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus Touring', 'minibus'),
  ('Volkswagen Crafter', 'Crafter Minibus Sport', 'minibus'),
  ('Iveco Daily', 'Daily Minibus', 'minibus'),
  ('Iveco Daily', 'Daily Tourys', 'minibus'),
  ('Iveco Daily', 'Daily City', 'minibus'),
  ('Iveco Daily', 'Daily 35S', 'minibus'),
  ('Iveco Daily', 'Daily 50C', 'minibus'),
  ('Iveco Daily', 'Daily 70C', 'minibus'),
  ('Iveco Daily', 'Daily L2H2', 'minibus'),
  ('Iveco Daily', 'Daily L3H2', 'minibus'),
  ('Iveco Daily', 'Daily L4H3', 'minibus'),
  ('Iveco Daily', 'Daily Electric Minibus', 'minibus'),
  ('Iveco Daily', 'Daily Commuter', 'minibus'),
  ('Iveco Daily', 'Daily School', 'minibus'),
  ('Iveco Daily', 'Daily Wheelchair', 'minibus'),
  ('Iveco Daily', 'Daily Minibus Hybrid', 'minibus'),
  ('Iveco Daily', 'Daily Minibus Electric', 'minibus'),
  ('Iveco Daily', 'Daily Minibus Plug-in Hybrid', 'minibus'),
  ('Iveco Daily', 'Daily Minibus Touring', 'minibus'),
  ('Iveco Daily', 'Daily Minibus Sport', 'minibus'),
  ('Renault Master', 'Master Minibus', 'minibus'),
  ('Renault Master', 'Master Combi', 'minibus'),
  ('Renault Master', 'Master L2H2', 'minibus'),
  ('Renault Master', 'Master L3H2', 'minibus'),
  ('Renault Master', 'Master Passenger', 'minibus'),
  ('Renault Master', 'Master City', 'minibus'),
  ('Renault Master', 'Master E-Tech Minibus', 'minibus'),
  ('Renault Master', 'Master Trail', 'minibus'),
  ('Renault Master', 'Master L4H3', 'minibus'),
  ('Renault Master', 'Master Shuttle', 'minibus'),
  ('Renault Master', 'Master School', 'minibus'),
  ('Renault Master', 'Master Mobility', 'minibus'),
  ('Renault Master', 'Master Minibus Hybrid', 'minibus'),
  ('Renault Master', 'Master Minibus Electric', 'minibus'),
  ('Renault Master', 'Master Minibus Plug-in Hybrid', 'minibus'),
  ('Renault Master', 'Master Minibus Touring', 'minibus'),
  ('Renault Master', 'Master Minibus Sport', 'minibus'),
  ('Renault Master', 'Master Minibus Limited', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus', 'minibus'),
  ('Peugeot Boxer', 'Boxer Combi', 'minibus'),
  ('Peugeot Boxer', 'Boxer L2H2', 'minibus'),
  ('Peugeot Boxer', 'Boxer L3H2', 'minibus'),
  ('Peugeot Boxer', 'Boxer L4H3', 'minibus'),
  ('Peugeot Boxer', 'Boxer 330', 'minibus'),
  ('Peugeot Boxer', 'Boxer 435', 'minibus'),
  ('Peugeot Boxer', 'Boxer Shuttle', 'minibus'),
  ('Peugeot Boxer', 'Boxer School', 'minibus'),
  ('Peugeot Boxer', 'Boxer Wheelchair', 'minibus'),
  ('Peugeot Boxer', 'e-Boxer Minibus', 'minibus'),
  ('Peugeot Boxer', 'Boxer City', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Hybrid', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Electric', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Plug-in Hybrid', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Touring', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Sport', 'minibus'),
  ('Peugeot Boxer', 'Boxer Minibus Limited', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus', 'minibus'),
  ('Fiat Ducato', 'Ducato Combi', 'minibus'),
  ('Fiat Ducato', 'Ducato L2H2', 'minibus'),
  ('Fiat Ducato', 'Ducato L3H2', 'minibus'),
  ('Fiat Ducato', 'Ducato L4H3', 'minibus'),
  ('Fiat Ducato', 'Ducato 33', 'minibus'),
  ('Fiat Ducato', 'Ducato 35', 'minibus'),
  ('Fiat Ducato', 'Ducato Shuttle', 'minibus'),
  ('Fiat Ducato', 'Ducato School', 'minibus'),
  ('Fiat Ducato', 'Ducato Wheelchair', 'minibus'),
  ('Fiat Ducato', 'Ducato City', 'minibus'),
  ('Fiat Ducato', 'Ducato Panorama', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Hybrid', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Electric', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Plug-in Hybrid', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Touring', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Sport', 'minibus'),
  ('Fiat Ducato', 'Ducato Minibus Limited', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus', 'minibus'),
  ('Nissan Interstar', 'Interstar Combi', 'minibus'),
  ('Nissan Interstar', 'NV400 Minibus', 'minibus'),
  ('Nissan Interstar', 'Civilian', 'minibus'),
  ('Nissan Interstar', 'Caravan Minibus', 'minibus'),
  ('Nissan Interstar', 'Interstar L2H2', 'minibus'),
  ('Nissan Interstar', 'Interstar L3H2', 'minibus'),
  ('Nissan Interstar', 'Interstar Shuttle', 'minibus'),
  ('Nissan Interstar', 'Interstar School', 'minibus'),
  ('Nissan Interstar', 'Interstar Commuter', 'minibus'),
  ('Nissan Interstar', 'Interstar Wheelchair', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Hybrid', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Electric', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Plug-in Hybrid', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Touring', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Sport', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Limited', 'minibus'),
  ('Nissan Interstar', 'Interstar Minibus Premium', 'minibus'),
  ('Opel Movano', 'Movano Minibus', 'minibus'),
  ('Opel Movano', 'Movano Combi', 'minibus'),
  ('Opel Movano', 'Movano L2H2', 'minibus'),
  ('Opel Movano', 'Movano L3H2', 'minibus'),
  ('Opel Movano', 'Movano Shuttle', 'minibus'),
  ('Opel Movano', 'Movano School', 'minibus'),
  ('Opel Movano', 'Movano City', 'minibus'),
  ('Opel Movano', 'Movano Wheelchair', 'minibus'),
  ('Opel Movano', 'Movano Commuter', 'minibus'),
  ('Opel Movano', 'Movano L4H3', 'minibus'),
  ('Opel Movano', 'Movano Minibus Hybrid', 'minibus'),
  ('Opel Movano', 'Movano Minibus Electric', 'minibus'),
  ('Opel Movano', 'Movano Minibus Plug-in Hybrid', 'minibus'),
  ('Opel Movano', 'Movano Minibus Touring', 'minibus'),
  ('Opel Movano', 'Movano Minibus Sport', 'minibus'),
  ('Opel Movano', 'Movano Minibus Limited', 'minibus'),
  ('Opel Movano', 'Movano Minibus Premium', 'minibus'),
  ('Opel Movano', 'Movano Minibus Executive', 'minibus'),
  ('MAN TGE', 'TGE Minibus', 'minibus'),
  ('MAN TGE', 'TGE Combi', 'minibus')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
