-- Part 6/9 — Models (NIO … Peugeot Traveller, 250 rows)
INSERT INTO public.vehicle_models (make_id, name, body_type)
SELECT vm.id, v.model_name, v.body_type
FROM (VALUES
  ('NIO', 'ET5', 'other'),
  ('NIO', 'ET5 Touring', 'wagon'),
  ('NIO', 'ET7', 'other'),
  ('NIO', 'EL6', 'other'),
  ('NIO', 'EL7', 'other'),
  ('NIO', 'EL8', 'other'),
  ('NIO', 'EC6', 'other'),
  ('NIO', 'EC7', 'other'),
  ('NIO', 'EP9', 'other'),
  ('NIO', 'ES6', 'other'),
  ('NIO', 'ES7', 'other'),
  ('NIO', 'ES8', 'other'),
  ('NIO', 'ET9', 'other'),
  ('NIO', 'Firefly', 'other'),
  ('NIO', 'Onvo L60', 'other'),
  ('NIO', 'Onvo L90', 'other'),
  ('NIO', 'ET5 Hybrid', 'other'),
  ('NIO', 'ET5 Electric', 'other'),
  ('MG', 'MG4', 'other'),
  ('MG', 'MG5', 'other'),
  ('MG', 'MG6', 'other'),
  ('MG', 'ZS', 'other'),
  ('MG', 'HS', 'other'),
  ('MG', 'Marvel R', 'other'),
  ('MG', 'Cyberster', 'other'),
  ('MG', 'TF', 'other'),
  ('MG', 'F', 'other'),
  ('MG', 'ZR', 'other'),
  ('MG', 'ZT', 'other'),
  ('MG', '3', 'other'),
  ('MG', 'Gloster', 'other'),
  ('MG', 'Hector', 'other'),
  ('MG', 'Astor', 'other'),
  ('MG', 'Comet', 'other'),
  ('MG', 'MGB', 'other'),
  ('MG', 'Midget', 'other'),
  ('Geely', 'Emgrand', 'other'),
  ('Geely', 'Coolray', 'other'),
  ('Geely', 'Azkarra', 'other'),
  ('Geely', 'Okavango', 'other'),
  ('Geely', 'Geometry C', 'other'),
  ('Geely', 'Geometry A', 'other'),
  ('Geely', 'Monjaro', 'other'),
  ('Geely', 'Tugella', 'other'),
  ('Geely', 'Preface', 'other'),
  ('Geely', 'Boyue', 'other'),
  ('Geely', 'Xingyue', 'other'),
  ('Geely', 'Icon', 'other'),
  ('Geely', 'Panda Mini EV', 'other'),
  ('Geely', 'Galaxy E8', 'van'),
  ('Geely', 'Galaxy L7', 'van'),
  ('Geely', 'Emgrand Hybrid', 'other'),
  ('Geely', 'Emgrand Electric', 'other'),
  ('Geely', 'Emgrand Plug-in Hybrid', 'other'),
  ('Chery', 'Tiggo 2', 'other'),
  ('Chery', 'Tiggo 3', 'other'),
  ('Chery', 'Tiggo 4', 'other'),
  ('Chery', 'Tiggo 7', 'other'),
  ('Chery', 'Tiggo 8', 'other'),
  ('Chery', 'Arrizo 5', 'other'),
  ('Chery', 'Arrizo 6', 'other'),
  ('Chery', 'Arrizo 8', 'other'),
  ('Chery', 'QQ', 'other'),
  ('Chery', 'Fulwin', 'other'),
  ('Chery', 'Omoda 5', 'other'),
  ('Chery', 'Jaecoo 7', 'other'),
  ('Chery', 'Exeed TX', 'other'),
  ('Chery', 'Exeed VX', 'other'),
  ('Chery', 'eQ1', 'other'),
  ('Chery', 'eQ7', 'other'),
  ('Chery', 'Tiggo 2 Hybrid', 'other'),
  ('Chery', 'Tiggo 2 Electric', 'other'),
  ('Haval', 'H6', 'other'),
  ('Haval', 'H9', 'other'),
  ('Haval', 'Jolion', 'other'),
  ('Haval', 'Dargo', 'other'),
  ('Haval', 'F7', 'other'),
  ('Haval', 'F7x', 'other'),
  ('Haval', 'H2', 'other'),
  ('Haval', 'H4', 'other'),
  ('Haval', 'Big Dog', 'other'),
  ('Haval', 'Xiaolong', 'other'),
  ('Haval', 'M6', 'other'),
  ('Haval', 'H6 GT', 'coupe'),
  ('Haval', 'H6 HEV', 'other'),
  ('Haval', 'Tank 300', 'other'),
  ('Haval', 'Tank 500', 'other'),
  ('Haval', 'H6 Hybrid', 'other'),
  ('Haval', 'H6 Electric', 'other'),
  ('Haval', 'H6 Plug-in Hybrid', 'other'),
  ('Tata', 'Nexon', 'other'),
  ('Tata', 'Punch', 'other'),
  ('Tata', 'Harrier', 'other'),
  ('Tata', 'Safari', 'other'),
  ('Tata', 'Tiago', 'other'),
  ('Tata', 'Tigor', 'other'),
  ('Tata', 'Altroz', 'other'),
  ('Tata', 'Curvv', 'other'),
  ('Tata', 'Sierra', 'pickup'),
  ('Tata', 'Indica', 'other'),
  ('Tata', 'Indigo', 'other'),
  ('Tata', 'Sumo', 'other'),
  ('Tata', 'Aria', 'other'),
  ('Tata', 'Bolt', 'other'),
  ('Tata', 'Zest', 'other'),
  ('Tata', 'Nano', 'other'),
  ('Tata', 'Hexa', 'other'),
  ('Tata', 'Nexon Hybrid', 'other'),
  ('Mahindra', 'Scorpio', 'other'),
  ('Mahindra', 'XUV700', 'other'),
  ('Mahindra', 'XUV300', 'other'),
  ('Mahindra', 'Thar', 'other'),
  ('Mahindra', 'Bolero', 'other'),
  ('Mahindra', 'Marazzo', 'other'),
  ('Mahindra', 'KUV100', 'other'),
  ('Mahindra', 'TUV300', 'other'),
  ('Mahindra', 'XUV400', 'other'),
  ('Mahindra', 'BE 6e', 'other'),
  ('Mahindra', 'XEV 9e', 'other'),
  ('Mahindra', 'Scorpio N', 'other'),
  ('Mahindra', 'Commander', 'other'),
  ('Mahindra', 'Armada', 'other'),
  ('Mahindra', 'Quanto', 'other'),
  ('Mahindra', 'Verito', 'other'),
  ('Mahindra', 'Scorpio Hybrid', 'other'),
  ('Mahindra', 'Scorpio Electric', 'other'),
  ('Smart', 'Fortwo', 'other'),
  ('Smart', 'Forfour', 'other'),
  ('Smart', '#1', 'other'),
  ('Smart', '#3', 'other'),
  ('Smart', '#5', 'other'),
  ('Smart', 'EQ Fortwo', 'other'),
  ('Smart', 'EQ Forfour', 'other'),
  ('Smart', 'Roadster', 'convertible'),
  ('Smart', 'Crossblade', 'other'),
  ('Smart', 'Brabus Fortwo', 'other'),
  ('Smart', 'Pulse', 'other'),
  ('Smart', 'Passion', 'other'),
  ('Smart', 'Prime', 'other'),
  ('Smart', 'Pure', 'other'),
  ('Smart', 'Fortwo Hybrid', 'other'),
  ('Smart', 'Fortwo Electric', 'other'),
  ('Smart', 'Fortwo Plug-in Hybrid', 'other'),
  ('Smart', 'Fortwo Touring', 'wagon'),
  ('Mercedes-Benz Vans', 'V-Class', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Marco Polo', 'van'),
  ('Mercedes-Benz Vans', 'Vito', 'van'),
  ('Mercedes-Benz Vans', 'Vito Tourer', 'van'),
  ('Mercedes-Benz Vans', 'EQV', 'van'),
  ('Mercedes-Benz Vans', 'Metris', 'van'),
  ('Mercedes-Benz Vans', 'Sprinter Passenger', 'van'),
  ('Mercedes-Benz Vans', 'eVito', 'van'),
  ('Mercedes-Benz Vans', 'Viano', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Exclusive', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Avantgarde', 'van'),
  ('Mercedes-Benz Vans', 'Vito Mixto', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Long', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Extra Long', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Hybrid', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Electric', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Plug-in Hybrid', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Touring', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Sport', 'van'),
  ('Mercedes-Benz Vans', 'V-Class Limited', 'van'),
  ('Volkswagen Van', 'Multivan', 'van'),
  ('Volkswagen Van', 'Caravelle', 'van'),
  ('Volkswagen Van', 'Transporter Kombi', 'van'),
  ('Volkswagen Van', 'ID. Buzz', 'van'),
  ('Volkswagen Van', 'Sharan', 'van'),
  ('Volkswagen Van', 'Touran', 'van'),
  ('Volkswagen Van', 'Caddy Maxi Life', 'van'),
  ('Volkswagen Van', 'California', 'van'),
  ('Volkswagen Van', 'Multivan Style', 'van'),
  ('Volkswagen Van', 'Caravelle Executive', 'van'),
  ('Volkswagen Van', 'Transporter Shuttle', 'van'),
  ('Volkswagen Van', 'Caddy Kombi', 'van'),
  ('Volkswagen Van', 'Multivan eHybrid', 'van'),
  ('Volkswagen Van', 'Grand California', 'van'),
  ('Volkswagen Van', 'Multivan Hybrid', 'van'),
  ('Volkswagen Van', 'Multivan Electric', 'van'),
  ('Volkswagen Van', 'Multivan Plug-in Hybrid', 'van'),
  ('Volkswagen Van', 'Multivan Touring', 'van'),
  ('Volkswagen Van', 'Multivan Sport', 'van'),
  ('Volkswagen Van', 'Multivan Limited', 'van'),
  ('Ford Tourneo', 'Tourneo Custom', 'van'),
  ('Ford Tourneo', 'Tourneo Connect', 'van'),
  ('Ford Tourneo', 'Tourneo Courier', 'van'),
  ('Ford Tourneo', 'Transit Connect Wagon', 'van'),
  ('Ford Tourneo', 'Galaxy', 'van'),
  ('Ford Tourneo', 'S-Max', 'van'),
  ('Ford Tourneo', 'Grand C-Max', 'van'),
  ('Ford Tourneo', 'Freestyle', 'van'),
  ('Ford Tourneo', 'Windstar', 'van'),
  ('Ford Tourneo', 'Aerostar', 'van'),
  ('Ford Tourneo', 'Transit Custom Kombi', 'van'),
  ('Ford Tourneo', 'Tourneo Active', 'van'),
  ('Ford Tourneo', 'E-Tourneo Custom', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Hybrid', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Electric', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Plug-in Hybrid', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Touring', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Sport', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Limited', 'van'),
  ('Ford Tourneo', 'Tourneo Custom Premium', 'van'),
  ('Renault Passenger', 'Trafic Passenger', 'van'),
  ('Renault Passenger', 'Trafic SpaceClass', 'van'),
  ('Renault Passenger', 'Espace', 'van'),
  ('Renault Passenger', 'Grand Espace', 'van'),
  ('Renault Passenger', 'Scenic', 'van'),
  ('Renault Passenger', 'Grand Scenic', 'van'),
  ('Renault Passenger', 'Kangoo', 'van'),
  ('Renault Passenger', 'Kangoo E-Tech', 'van'),
  ('Renault Passenger', 'Trafic Combi', 'van'),
  ('Renault Passenger', 'Master Passenger', 'van'),
  ('Renault Passenger', 'Arkana Space', 'van'),
  ('Renault Passenger', 'Rafale', 'van'),
  ('Renault Passenger', 'Trafic Passenger Hybrid', 'van'),
  ('Renault Passenger', 'Trafic Passenger Electric', 'van'),
  ('Renault Passenger', 'Trafic Passenger Plug-in Hybrid', 'van'),
  ('Renault Passenger', 'Trafic Passenger Touring', 'van'),
  ('Renault Passenger', 'Trafic Passenger Sport', 'van'),
  ('Renault Passenger', 'Trafic Passenger Limited', 'van'),
  ('Nissan Passenger Van', 'Serena', 'van'),
  ('Nissan Passenger Van', 'NV350 Caravan', 'van'),
  ('Nissan Passenger Van', 'Elgrand', 'van'),
  ('Nissan Passenger Van', 'Quest', 'van'),
  ('Nissan Passenger Van', 'NV200', 'van'),
  ('Nissan Passenger Van', 'NV300 Combi', 'van'),
  ('Nissan Passenger Van', 'Primastar Passenger', 'van'),
  ('Nissan Passenger Van', 'Townstar', 'van'),
  ('Nissan Passenger Van', 'e-NV200', 'van'),
  ('Nissan Passenger Van', 'Serena e-Power', 'van'),
  ('Nissan Passenger Van', 'Lafesta', 'van'),
  ('Nissan Passenger Van', 'Presage', 'van'),
  ('Nissan Passenger Van', 'Serena Hybrid', 'van'),
  ('Nissan Passenger Van', 'Serena Electric', 'van'),
  ('Nissan Passenger Van', 'Serena Plug-in Hybrid', 'van'),
  ('Nissan Passenger Van', 'Serena Touring', 'van'),
  ('Nissan Passenger Van', 'Serena Sport', 'van'),
  ('Nissan Passenger Van', 'Serena Limited', 'van'),
  ('Peugeot Traveller', 'Traveller', 'van'),
  ('Peugeot Traveller', 'Rifter', 'van'),
  ('Peugeot Traveller', 'Partner Tepee', 'van'),
  ('Peugeot Traveller', 'Expert Tepee', 'van'),
  ('Peugeot Traveller', '5008', 'van'),
  ('Peugeot Traveller', '807', 'van'),
  ('Peugeot Traveller', '806', 'van'),
  ('Peugeot Traveller', 'Expert Combi', 'van'),
  ('Peugeot Traveller', 'Traveller Business', 'van'),
  ('Peugeot Traveller', 'e-Traveller', 'van')
) AS v(make_name, model_name, body_type)
JOIN public.vehicle_makes vm ON vm.name = v.make_name
ON CONFLICT (make_id, name) DO NOTHING;
